#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Task 002: Persistent State Across Scanner Restarts

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT CHECK
# ============================================

echo "Checking Python environment..."
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi
echo -e "${GREEN}Python 3 found: $(python3 --version)${NC}"

echo "Checking Node.js environment..."
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found${NC}"
    exit 1
fi
echo -e "${GREEN}Node.js found: $(node --version)${NC}"

# ============================================
# DEPENDENCIES
# ============================================

echo ""
echo "Installing/verifying Node.js dependencies..."
npm install

echo ""
echo "Verifying TradingView MCP tools..."
if ! command -v node src/cli/index.js &> /dev/null; then
    echo -e "${YELLOW}Warning: TradingView CLI not accessible${NC}"
fi

# ============================================
# STATE FILES CHECK
# ============================================

echo ""
echo "Checking existing state files..."
STATE_FILES=$(ls ~/.tv_fast_*.json 2>/dev/null | wc -l)
if [ "$STATE_FILES" -gt 0 ]; then
    echo -e "${YELLOW}Found $STATE_FILES existing state files in ~/.tv_fast_*${NC}"
    echo "These will be migrated to consolidated StateManager"
else
    echo "No existing state files found (clean start)"
fi

# ============================================
# CREATE LOGS DIRECTORY
# ============================================

echo ""
echo "Setting up logs directory structure..."
mkdir -p logs/_orch
for symbol in XAUUSD GBPUSD NAS100 US30 EURUSD USDJPY AUDUSD; do
    mkdir -p logs/$symbol
done
echo -e "${GREEN}Logs directories created${NC}"

# ============================================
# VERIFY INSTRUMENTS CONFIG
# ============================================

echo ""
echo "Verifying instruments configuration..."
if [ -f "instruments.json" ]; then
    echo -e "${GREEN}instruments.json found${NC}"
    python3 -c "import json; c = json.load(open('instruments.json')); print(f'Configured instruments: {[k for k in c if not k.startswith(\"_\")]}')"
else
    echo -e "${RED}instruments.json not found${NC}"
    exit 1
fi

# ============================================
# TEST IMPORTS
# ============================================

echo ""
echo "Testing Python imports..."
python3 -c "import subprocess, json, os, sys, time, datetime" && echo -e "${GREEN}Core imports OK${NC}"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Development commands:"
echo "  Test scanner:     python3 scalp_fast.py --symbol XAUUSD"
echo "  Test orchestrator: python3 orchestrate.py"
echo "  Run meta-scan:    python3 scan_pairs.py"
echo ""
echo "State files location: ~/.tv_fast_*.json"
echo "Logs location: ./logs/"
echo ""
echo "Ready to implement StateManager consolidation."
echo ""
